### ISSUE TITLE
Renormalization issue in Kromer Plot

### ISSUE THREAD

**Issue by unoebauer** [tardis-sn/tardisanalysis#10]
The current normalization of the Kromer plot only works if the binning used in the histogram encompasses the bulk of the escaping packets. Instead of 

``` python
Lnorm = 0
for w in weights:
    Lnorm += np.sum(w)
```

the following expression should be used:

``` python
Lnorm = 0
for w, lam in zip(weights, lams):
    Lnorm += np.sum(w[(lam >= self.bins[0]) * (lam <= self.bins[-1])])
```

**Comment by jamesgillanders** [comment]
See PR #31
